language: cpp
os:
    - linux
    - osx
compiler:
    - clang
    - gcc
matrix:
    exclude:
        - compiler: gcc
        - os: osx
before_install:
    - if [ $TRAVIS_OS_NAME == osx ]; then curl http://www.cmake.org/files/v3.0/cmake-3.0.2-Darwin64-universal.tar.gz -o cmake.tar.gz; fi
    - if [ $TRAVIS_OS_NAME == osx ]; then tar xzf cmake.tar.gz; fi
    - if [ $TRAVIS_OS_NAME == osx ]; then export PATH=$PATH:"cmake-3.0.2-Darwin64-universal/CMake.app/Contents/bin"; fi
    - git submodule update --init
env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
    - CTEST_OUTPUT_ON_FAILURE=1 make -j4 check
    - cd .. && rm -rf build/