language: cpp
script: cmake

matrix:
    include:
        # Clang
        - env: CLANG_VERSION=3.4 BUILD_TYPE=Debug ASAN=on LIBCXX=on
          os: linux
          compiler: clang34
          addons: &clang34
            apt:
              packages:
                - valgrind
              sources:
                - ubuntu-toolchain-r-test

        - env: CLANG_VERSION=3.4 BUILD_TYPE=Debug ASAN=on LIBCXX=off
          os: linux
          compiler: clang
          addons: *clang34

        - env: CLANG_VERSION=3.7 BUILD_TYPE=Debug ASAN=on LIBCXX=on
          os: linux
          addons: &clang37
            apt:
              packages:
                - clang-3.7
                - valgrind
              sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-precise

        - env: CLANG_VERSION=3.7 BUILD_TYPE=Debug ASAN=on LIBCXX=off
          os: linux
          addons: *clang37

        - env: GCC_VERSION=4.9 BUILD_TYPE=Debug ASAN=off LIBCXX=off
          os: linux
          addons: &gcc49
            apt:
              packages:
                - g++-4.9
                - valgrind
              sources:
                - ubuntu-toolchain-r-test

        - env: GCC_VERSION=4.8 BUILD_TYPE=Debug ASAN=off LIBCXX=off
          os: linux
          addons: &gcc48
            apt:
              packages:
                - g++-4.8
                - valgrind
              sources:
                - ubuntu-toolchain-r-test


        - env: GCC_VERSION=4.7 BUILD_TYPE=Debug ASAN=off LIBCXX=off
          os: linux
          addons: &gcc47
            apt:
              packages:
                - g++-4.7
                - valgrind
              sources:
                - ubuntu-toolchain-r-test

        - env: GCC_VERSION=4.6 BUILD_TYPE=Debug ASAN=off LIBCXX=off
          os: linux
          addons: &gcc46
            apt:
              packages:
                - g++-4.6
                - valgrind
              sources:
                - ubuntu-toolchain-r-test

before_install:
    - export CHECKOUT_PATH=`pwd`;
    - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
    - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
    - if [ "$CLANG_VERSION" == "3.4" ]; then export CXX="/usr/local/clang-3.4/bin/clang++" CC="/usr/local/clang-3.4/bin/clang"; fi
    - export CXX_FLAGS="-Wall -Wextra -Werror"
    # Install cmake
    - wget http://www.cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.sh
    - sudo sh cmake-3.1.3-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir
    # Show compiler info
    - $CXX --version
    - which $CXX
    - $CC --version
    - which $CC
    # Install libc++
    - if [ "$LIBCXX" = "on" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
    - if [ "$LIBCXX" = "on" ]; then cd libcxx/lib && bash buildit; fi
    - if [ "$LIBCXX" = "on" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
    - if [ "$LIBCXX" = "on" ]; then sudo mkdir /usr/include/c++/v1; fi
    - if [ "$LIBCXX" = "on" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
    - if [ "$LIBCXX" = "on" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
    - if [ "$LIBCXX" = "on" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi

script:
    - cd $CHECKOUT_PATH
    - if [ ! -d build ]; then mkdir build; fi
    - cd build
    - if [ "$ASAN" == "on"]; then export CXX_FLAGS="${CXX_FLAGS} -fsanitize=address,undefined,integer -fno-omit-frame-pointer -fno-sanitize=unsigned-integer-overflow"; fi
    - if [ "$LIBCXX" = "on" ]; then CXX_FLAGS="${CXX_FLAGS} -stdlib=libc++ -I/usr/include/c++/v1/"; fi
    - if [ "$LIBCXX" = "on" ]; then CXX_LINKER_FLAGS="${CXX_FLAGS} -L/usr/lib/ -lc++"; fi
    - if [ "$ENABLE_BUILD" = "on" ]; then cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" -DCMAKE_EXE_LINKER_FLAGS="${CXX_LINKER_FLAGS}" ..; fi
    - if [ "$ENABLE_BUILD" = "on" ]; then CTEST_OUTPUT_ON_FAILURE=1 make -j4 check VERBOSE=1; fi
    - cd .. && rm -rf build/

