language: cpp
os:
    - linux
matrix:
    include:
        - compiler: gcc
          env:
            - GCC_VERSION="4.9"
            - CXX_FLAGS="-Wall -Wextra -Werror"
          addons: &gcc49
            apt:
              packages:
                - g++-4.9
                - valgrind
              sources:
                - ubuntu-toolchain-r-test
        - compiler: gcc
          env: 
            - GCC_VERSION="4.8"
            - CXX_FLAGS="-Wall -Wextra -Werror"
          addons: &gcc48
            apt:
              packages:
                - g++-4.8
                - valgrind
              sources:
                - ubuntu-toolchain-r-test
        - compiler: gcc
          env: 
            - GCC_VERSION="4.7"
            - CXX_FLAGS="-Wall -Wextra -Werror"
          addons: &gcc47
            apt:
              packages:
                - g++-4.7
                - valgrind
              sources:
                - ubuntu-toolchain-r-test
        - compiler: gcc
          env: 
            - GCC_VERSION="4.6"
            - CXX_FLAGS="-Wall -Wextra -Werror"
          addons: &gcc46
            apt:
              packages:
                - g++-4.8
                - valgrind
              sources:
                - ubuntu-toolchain-r-test
        - compiler: clang
          env: 
            - CLANG_VERSION="3.4"
            - LIBCXX="on"
            - CXX_FLAGS="-Wall -Wextra -Werror"
          addons: &clang34
            apt:
              packages:
                - valgrind
              sources:
                - ubuntu-toolchain-r-test
        - compiler: clang
          env: 
            - CLANG_VERSION="3.4"
            - LIBCXX="off"
            - CXX_FLAGS="-Wall -Wextra -Werror"
          addons: *clang34
        - compiler: clang
          env: 
            - CLANG_VERSION="3.6"
            - LIBCXX="on"
            - CXX_FLAGS="-Wall -Wextra -Werror"
          addons: &clang36
            apt:
              packages:
                - g++-4.9
                - clang-3.6
                - valgrind
              sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-precise
        - compiler: clang
          env: 
            - CLANG_VERSION="3.6"
            - LIBCXX="off"
            - CXX_FLAGS="-Wall -Wextra -Werror"
          addons: *clang36

before_install:
    - export CHECKOUT_PATH=`pwd`;
    # Install cmake
    - wget http://www.cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.sh
    - sudo sh cmake-3.1.3-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir
    # Setup environment
    - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
    - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
    - if [ "$CLANG_VERSION" == "3.4" ]; then export CXX="clang++" CC="clang"; fi

    # Install libc++
    - if [ "$LIBCXX" = "on" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
    - if [ "$LIBCXX" = "on" ]; then cd libcxx/lib && bash buildit; fi
    - if [ "$LIBCXX" = "on" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
    - if [ "$LIBCXX" = "on" ]; then sudo mkdir /usr/include/c++/v1; fi
    - if [ "$LIBCXX" = "on" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
    - if [ "$LIBCXX" = "on" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
    - if [ "$LIBCXX" = "on" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi
    # Info
    - $CXX --version
    - $CC --version
    - which $CXX
    - which $CC
    - which valgrind

script:
    - cd $CHECKOUT_PATH
    - if [ ! -d build ]; then mkdir build; fi
    - cd build
    - if [ "$LIBCXX" = "on" ]; then CXX_FLAGS="${CXX_FLAGS} -stdlib=libc++ -I/usr/include/c++/v1/"; fi
    - if [ "$LIBCXX" = "on" ]; then CXX_LINKER_FLAGS="${CXX_FLAGS} -L/usr/lib/ -lc++"; fi
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" -DCMAKE_EXE_LINKER_FLAGS="${CXX_LINKER_FLAGS}" ..
    - CTEST_OUTPUT_ON_FAILURE=1 make -j4 check VERBOSE=1
    - cd .. && rm -rf build/

