
environment:
  matrix:
  - GENERATOR: "Visual Studio 14 2015 Win64"
    CONFIG: Debug
    VS_VERSION: "14.0"

  - GENERATOR: "Visual Studio 14 2015 Win64"
    CONFIG: Release
    VS_VERSION: "14.0"

matrix:
  fast_finish: true

before_build:
 - git submodule update --init --recursive

build_script:
 - cmd: set PATH=C:\Program Files (x86)\CMake\bin;%PATH%
 - cmd: call "C:/Program Files (x86)/Microsoft Visual Studio %VS_VERSION%/Common7/Tools/vsvars32.bat"
 - cmd: cmake --version
 - cmd: cd tests
 - cmd: mkdir build
 - cmd: cd build
 - cmd: cmake .. -Wdev --warn-uninitialized -G"%GENERATOR%"
 - cmd: cmake --build . --target check

# test_script:
#  - cmd: ctest -C Debug --output-on-failure
#  - cmd: cd ../../