
environment:
  matrix:
  - GENERATOR: "Visual Studio 14 2015 Win64"
    CONFIG: Debug

  - GENERATOR: "Visual Studio 14 2015 Win64"
    CONFIG: Release

matrix:
  fast_finish: true

build_script:
 - cmd: set PATH=C:\Program Files (x86)\CMake\bin;%PATH%
 - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
 # - cmd: call "C:/Program Files (x86)/Microsoft Visual Studio %VS_VERSION%/Common7/Tools/vsvars32.bat"
 - cmd: cmake --version
 - cmd: cd tests
 - cmd: mkdir build
 - cmd: cd build
 - cmd: cmake .. -Wdev --warn-uninitialized -G"%GENERATOR%"
 - cmd: cmake --build . --target check

# test_script:
#  - cmd: ctest -C Debug --output-on-failure
#  - cmd: cd ../../