site_name: Fit
docs_dir: doc/src
site_dir: doc/html/
repo_url: https://github.com/pfultz2/Fit
copyright: 'Copyright &#169; 2014 Paul Fultz II'
site_author: 'Paul Fultz II'
use_directory_urls: false
extra_javascript: [js/configure.js]
theme: readthedocs
pages:
- Home: 'index.md'
- About:
    - 'quickstart.md'
    - 'more_examples.md'
    - 'overview.md'
    - 'concepts.md'
    - 'configurations.md'
    - 'requirements.md'
    - 'faq.md'
    - 'acknowledgements.md'
    - 'license.md'
- Adaptors:
    - 'by.md'
    - 'compose.md'
    - 'conditional.md'
    - 'combine.md'
    - 'compress.md'
    - 'decorate.md'
    - 'fix.md'
    - 'flip.md'
    - 'flow.md'
    - 'implicit.md'
    - 'indirect.md'
    - 'infix.md'
    - 'lazy.md'
    - 'match.md'
    - 'mutable.md'
    - 'partial.md'
    - 'pipable.md'
    - 'protect.md'
    - 'result.md'
    - 'reveal.md'
    - 'reverse_compress.md'
    - 'rotate.md'
    - 'static.md'
    - 'unpack.md'
- Decorators:
    - 'capture.md'
    - 'if.md'
    - 'limit.md'
    - 'repeat.md'
    - 'repeat_while.md'
- Functions:
    - 'always.md'
    - 'arg.md'
    - 'construct.md'
    - 'decay.md'
    - 'identity.md'
    - 'placeholders.md'
- Utilities:
    - 'alias.md'
    - 'apply.md'
    - 'apply_eval.md'
    - 'eval.md'
    - 'function.md'
    - 'lambda.md'
    - 'lift.md'
    - 'is_callable.md'
    - 'pack.md'
    - 'returns.md'
    - 'tap.md'
